# Generated by Django 6.0.2 on 2026-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_bouwdossier_dossiernr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
