# Generated by Django 4.1.13 on 2024-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buurt',
            name='buurtcombinatie',
        ),
        migrations.RemoveField(
            model_name='rijrijtjeshuizen',
            name='bouwblok',
        ),
        migrations.RemoveField(
            model_name='rijtjeshuis',
            name='pand',
        ),
        migrations.RemoveField(
            model_name='rijtjeshuis',
            name='rij',
        ),
        migrations.RemoveField(
            model_name='wijk',
            name='stadsdeel',
        ),
        migrations.AlterField(
            model_name='ligplaats',
            name='buurt',
            field=models.CharField(db_column='ligtinbuurtid', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pand',
            name='bouwblok',
            field=models.CharField(db_column='ligtinbouwblokid', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pand',
            name='buurt',
            field=models.CharField(db_column='ligtinbuurtid', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='standplaats',
            name='buurt',
            field=models.CharField(db_column='ligtinbuurtid', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='verblijfsobject',
            name='buurt',
            field=models.CharField(db_column='ligtinbuurtid', max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Bouwblok',
        ),
        migrations.DeleteModel(
            name='Buurt',
        ),
        migrations.DeleteModel(
            name='RijRijtjeshuizen',
        ),
        migrations.DeleteModel(
            name='Rijtjeshuis',
        ),
        migrations.DeleteModel(
            name='Stadsdeel',
        ),
        migrations.DeleteModel(
            name='Wijk',
        ),
    ]
