# Generated by Django 4.1.13 on 2024-02-19 12:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pand',
            managers=[
                ('transformed_geo_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='verblijfsobject',
            managers=[
                ('transformed_geo_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ligplaats',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nummeraanduiding',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='openbareruimte',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pand',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='standplaats',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='verblijfsobject',
            name='plusvolgnummer',
            field=models.IntegerField(null=True),
        ),
    ]
