# Generated by Django 4.1.13 on 2024-03-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bag", "0003_alter_pand_bouwblok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openbareruimte",
            name="naam_nen",
            field=models.CharField(db_column="naamnen", max_length=80, null=True),
        ),
    ]
