# Generated by Django 4.1.13 on 2024-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bag", "0004_alter_openbareruimte_naam_nen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openbareruimte",
            name="document_nummer",
            field=models.CharField(db_column="documentnummer", max_length=40),
        ),
    ]
