# Generated by Django 5.1.3 on 2024-12-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bag", "0004_alter_openbareruimte_naam_nen"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagUpdatedAt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ligplaats",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="ligplaats",
            name="document_nummer",
        ),
        migrations.RemoveField(
            model_name="nummeraanduiding",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="nummeraanduiding",
            name="document_nummer",
        ),
        migrations.RemoveField(
            model_name="openbareruimte",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="openbareruimte",
            name="document_nummer",
        ),
        migrations.RemoveField(
            model_name="pand",
            name="bouwjaar",
        ),
        migrations.RemoveField(
            model_name="pand",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="pand",
            name="document_nummer",
        ),
        migrations.RemoveField(
            model_name="pand",
            name="hoogste_bouwlaag",
        ),
        migrations.RemoveField(
            model_name="pand",
            name="laagste_bouwlaag",
        ),
        migrations.RemoveField(
            model_name="standplaats",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="standplaats",
            name="document_nummer",
        ),
        migrations.RemoveField(
            model_name="verblijfsobject",
            name="document_mutatie",
        ),
        migrations.RemoveField(
            model_name="verblijfsobject",
            name="document_nummer",
        ),
        migrations.AlterField(
            model_name="openbareruimte",
            name="geconstateerd",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="verblijfsobjectpandrelatie",
            name="pand",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="bag.pand"
            ),
        ),
        migrations.AlterField(
            model_name="verblijfsobjectpandrelatie",
            name="verblijfsobject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bag.verblijfsobject",
            ),
        ),
    ]
