# Generated by Django 5.1.3 on 2025-01-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bag", "0005_bagupdatedat_remove_ligplaats_document_mutatie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verblijfsobjectpandrelatie",
            name="pand",
            field=models.ForeignKey(
                db_column="ligtinpandenidentificatie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bag.pand",
            ),
        ),
        migrations.AlterField(
            model_name="verblijfsobjectpandrelatie",
            name="verblijfsobject",
            field=models.ForeignKey(
                blank=True,
                db_column="verblijfsobjectenidentificatie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bag.verblijfsobject",
            ),
        ),
    ]
