# Generated by Django 6.0.2 on 2026-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bag", "0006_alter_verblijfsobjectpandrelatie_pand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bagupdatedat",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
