SOURCE_EDEPOT = "EDEPOT"
SOURCE_WABO = "WABO"

ACCESS_PUBLIC = "PUBLIC"
ACCESS_RESTRICTED = "RESTRICTED"

COPYRIGHT_YES = "Y"
COPYRIGHT_NO = "N"

STATUS_AANVRAAG = "A"
STATUS_BEHANDELING = "B"

IMPORT_BUSY = "B"
IMPORT_FINISHED = "F"
IMPORT_ERROR = "E"
