# Generated by Django 2.2 on 2019-04-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straat', models.CharField(max_length=150)),
                ('huisnummer_van', models.IntegerField()),
                ('huisnummer_tot', models.IntegerField()),
                ('_openbareruimte', models.CharField(max_length=16, unique=True)),
                ('_stadsdeel', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bouwdossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dossiernr', models.CharField(db_index=True, max_length=16)),
                ('titel', models.CharField(db_index=True, max_length=512)),
                ('datering', models.CharField(max_length=4, null=True)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(db_index=True, max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('bouwdossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdossier', to='bouwdossiers.Bouwdossier')),
            ],
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(max_length=16, unique=True)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pand', to='bouwdossiers.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Nummeraanduiding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(max_length=16, unique=True)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nummeraanduiding', to='bouwdossiers.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Bestand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('subdossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestand', to='bouwdossiers.SubDossier')),
            ],
        ),
        migrations.AddField(
            model_name='adres',
            name='bouwdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres', to='bouwdossiers.Bouwdossier'),
        ),
    ]
