# Generated by Django 2.2.14 on 2020-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bouwdossiers", "0003_auto_20200501_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adres",
            name="stadsdeel",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="bouwdossier",
            name="stadsdeel",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
