# Generated by Django 4.1.13 on 2024-02-13 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bouwdossiers", "0006_auto_20201228_1449"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouwdossier",
            options={},
        ),
    ]
