# Generated by Django 5.1.5 on 2025-01-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bouwdossiers", "0007_alter_bouwdossier_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouwdossier",
            name="dossiernr",
            field=models.CharField(max_length=75),
        ),
    ]
