# Generated by Django 6.0.2 on 2026-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bouwdossiers", "0008_alter_bouwdossier_dossiernr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouwdossier",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="document",
            name="document_omschrijving",
            field=models.TextField(blank=True, null=True),
        ),
    ]
