# Generated by Django 2.1.7 on 2019-04-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straat', models.CharField(max_length=150)),
                ('huisnummer_van', models.IntegerField()),
                ('huisnummer_tot', models.IntegerField()),
                ('openbareruimte_id', models.CharField(db_index=True, max_length=16)),
                ('stadsdeel', models.CharField(db_index=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bestand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BouwDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dossiernr', models.CharField(db_index=True, max_length=16)),
                ('stadsdeel', models.CharField(db_index=True, max_length=3)),
                ('titel', models.CharField(db_index=True, max_length=512)),
                ('datering', models.CharField(max_length=4, null=True)),
                ('dossier_type', models.CharField(max_length=64, null=True)),
                ('dossier_status',
                 models.CharField(choices=[('A', 'Aanvraag'), ('B', 'Behandeling')], max_length=1, null=True)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
            ],
            options={
                'ordering': ('stadsdeel', 'dossiernr'),
            },
        ),
        migrations.CreateModel(
            name='Nummeraanduiding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(db_index=True, max_length=16)),
                ('adres',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nummeraanduidingen',
                                   to='stadsarchief.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(db_index=True, max_length=16)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panden',
                                            to='stadsarchief.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='SubDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(db_index=True, max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('bouwdossier',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdossiers',
                                   to='stadsarchief.BouwDossier')),
            ],
        ),
        migrations.AddField(
            model_name='bestand',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestand',
                                    to='stadsarchief.BouwDossier'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='subdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestanden',
                                    to='stadsarchief.SubDossier'),
        ),
        migrations.AddField(
            model_name='adres',
            name='bouwdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressen',
                                    to='stadsarchief.BouwDossier'),
        ),
    ]
