# Generated by Django 2.2 on 2019-04-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straat', models.CharField(max_length=150)),
                ('huisnummer_van', models.IntegerField()),
                ('huisnummer_tot', models.IntegerField()),
                ('_openbareruimte', models.CharField(db_index=True, max_length=16)),
                ('_stadsdeel', models.CharField(db_index=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bouwdossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dossiernr', models.CharField(db_index=True, max_length=16)),
                ('titel', models.CharField(db_index=True, max_length=512)),
                ('datering', models.CharField(max_length=4, null=True)),
                ('dossier_type', models.CharField(max_length=64, null=True)),
                ('dossier_status', models.CharField(choices=[('A', 'Aanvraag'), ('B', 'Behandeling')], max_length=1, null=True)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
            ],
            options={
                'ordering': ('dossiernr',),
            },
        ),
        migrations.CreateModel(
            name='SubDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(db_index=True, max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('bouwdossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdossier', to='stadsarchief.Bouwdossier')),
            ],
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(db_index=True, max_length=16)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pand', to='stadsarchief.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Nummeraanduiding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landelijk_id', models.CharField(db_index=True, max_length=16)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nummeraanduiding', to='stadsarchief.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Bestand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('subdossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestand', to='stadsarchief.SubDossier')),
            ],
        ),
        migrations.AddField(
            model_name='adres',
            name='bouwdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres', to='stadsarchief.Bouwdossier'),
        ),
    ]
