# Generated by Django 2.1.7 on 2019-04-16 09:02

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straat', models.CharField(max_length=150)),
                ('huisnummer_van', models.IntegerField(null=True)),
                ('huisnummer_tot', models.IntegerField(null=True)),
                ('openbareruimte_id', models.CharField(db_index=True, max_length=16)),
                ('stadsdeel', models.CharField(db_index=True, max_length=3)),
                ('nummeraanduidingen', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, size=None)),
                ('panden', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='BouwDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dossiernr', models.CharField(db_index=True, max_length=16)),
                ('stadsdeel', models.CharField(db_index=True, max_length=3)),
                ('titel', models.CharField(db_index=True, max_length=512)),
                ('datering', models.DateField(null=True)),
                ('dossier_type', models.CharField(max_length=64, null=True)),
                ('dossier_status', models.CharField(choices=[('A', 'Aanvraag'), ('B', 'Behandeling')], max_length=1, null=True)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
            ],
            options={
                'ordering': ('stadsdeel', 'dossiernr'),
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('B', 'Busy'), ('F', 'Finished'), ('E', 'Error')], max_length=1)),
                ('last_import', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(db_index=True, max_length=128)),
                ('bestanden', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, size=None)),
                ('access', models.CharField(choices=[('P', 'Public'), ('R', 'Restricted')], max_length=1, null=True)),
                ('bouwdossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdossiers', to='stadsarchief.BouwDossier')),
            ],
        ),
        migrations.AddField(
            model_name='bouwdossier',
            name='importfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouwdossiers', to='stadsarchief.ImportFile'),
        ),
        migrations.AddField(
            model_name='adres',
            name='bouwdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='stadsarchief.BouwDossier'),
        ),
        migrations.AddIndex(
            model_name='adres',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nummeraanduidingen'], name='stadsarchie_nummera_47fb2b_gin'),
        ),
        migrations.AddIndex(
            model_name='adres',
            index=django.contrib.postgres.indexes.GinIndex(fields=['panden'], name='stadsarchie_panden_580144_gin'),
        ),
    ]
