# Generated by Django 2.1.7 on 2019-05-20 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadsarchief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='verblijfsobjecten',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=None, size=None),
            preserve_default=False,
        ),
    ]

