# Generated by Django 2.2.8 on 2020-01-21 12:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadsarchief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subdossier_titel', models.CharField(max_length=128)),
                ('barcode', models.CharField(db_index=True, max_length=250)),
                ('bestanden', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, size=None)),
                ('access', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bouwdossier',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SubDossier',
        ),
        migrations.AddField(
            model_name='document',
            name='bouwdossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenten', to='stadsarchief.BouwDossier'),
        ),
    ]
