# Generated by Django 2.2.10 on 2020-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadsarchief', '0002_auto_20200121_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouwdossier',
            name='source',
            field=models.CharField(choices=[('EDEPOT', 'edepot'), ('WABO', 'wabo')], default='EDEPOT', max_length=20),
        ),
    ]
