tenantId: 72fca1b1-2c2e-4376-a445-294d80196804  # Global

# Default keyvault for getting secrets
keyVaultName: bouwdossiers-o-i5sk6etz4  # App specific

# Identity AppID (clientId) used to authenticate with the keyvault
workloadIdentity: f8e00e39-a13c-43c1-b7c0-7c89f19c068d  # Environment specific

# We must select the nodepool to run the pods on
nodepool: cccopdront01  # Environment specific

# Default host for the ingress resources
host: bouwdossiers.opdr-o.azure.amsterdam.nl  # App specific

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-o-yhqbd6yktpphi  # Environment specific

  database:
    type: opaque
    secrets:
      database-host: bouwdossiers-o-i5sk6etz4.postgres.database.azure.com  # Environment specific
      database-name: iiif-metadata-server
      database-user: bouwdossiers-app-o  # Environment specific

ingress:
  app:
    className: nginx-internal  # App specific
