host: localhost

jobs:
  certificate-init:
    enabled: false

ingress:
  app:
    tls: null

secrets:
  certificate:
    enabled: false
  
  database:
    type: opaque
    secrets:
      database-host: database-iiif-metadata-server
      database-name: dev
      database-user: dev

  vault:
    type: opaque
    secrets:
      secret-key: dev
      keycloak-jwks-url: dev
      use-jwks-test-key: "true"
      # sentry-dsn: dev
      # sentry-environment: dev
      # pub-jwks: dev
      # hcp-authorization: dev
      # iiif-image-server-wabo-cert: ZGV2
      # start-stunnel: "true"
      # jwt-secret-key: dev
      # os-username: bouwdossiers
      # os-password: dev
      # os-auth-url: https://identity.stack.cloudvps.com/v2.0
      # os-tenant-name: BGE000081 Bouwdossier
      # os-tenant-id: 9d078258c1a547c09e0b5f88834554f1
      # os-container-name: downloads_acceptance
      # os-temp-url-key: dev
      # allow-localhost-login-url: "true"
      # email-host: smr.amsterdam.nl
      # email-host-user: Srvc_Bouwdossiers@amsterdam.nl
      # email-host-password: dev



network:
  allow-ingress:
    enabled: false